"""
helpers.py — Utility functions shared across the application.
"""

import os
from pathlib import Path


def format_minutes_output(raw_text: str, filename: str) -> str:
    """
    Add a professional header to the generated minutes.

    Args:
        raw_text: Raw output from the LLM
        filename: Name of the source transcript file

    Returns:
        Formatted meeting minutes with header
    """
    from datetime import datetime
    date_str = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    header = f"""MEETING MINUTES
Generated by AI Meeting Minutes Generator
Source: {filename}
Generated: {date_str}
{'─' * 60}

"""
    return header + raw_text


def clean_text(text: str) -> str:
    """Remove extra whitespace and normalize line endings."""
    import re
    # Normalize line endings
    text = text.replace('\r\n', '\n').replace('\r', '\n')
    # Remove excessive blank lines (more than 2 consecutive)
    text = re.sub(r'\n{3,}', '\n\n', text)
    # Remove trailing whitespace from each line
    text = '\n'.join(line.rstrip() for line in text.split('\n'))
    return text.strip()


def get_file_info(file_path: str) -> dict:
    """Get basic file metadata."""
    path = Path(file_path)
    stat = path.stat()
    return {
        "name": path.name,
        "size_bytes": stat.st_size,
        "size_kb": round(stat.st_size / 1024, 2),
        "extension": path.suffix,
    }